# Generated by Django 4.1.3 on 2023-07-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvcapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='qtyAvailable',
            new_name='qty_available',
        ),
    ]
